CREATE DATABASE TAXCODE_APPLICATION;

DROP TABLE IF EXISTS CITIES;
CREATE TABLE CITIES (
  ID int NOT NULL AUTO_INCREMENT,
  NAME varchar(255) NOT NULL,
  CITY_CODE varchaR(6) NOT NULL,
  CATASTO_CODE varchaR(4) NOT NULL,
  PRIMARY KEY (ID));