package it.beergash.taxcodeApplication.exception;

import it.beergash.taxcodeApplication.service.CityCodeService;

/**
 * Exception handling errors generated by @{@link CityCodeService}
 *
 * @author A.Aresta
 */
public class CityServiceException extends RuntimeException {

    public CityServiceException() {
    }

    public CityServiceException(String s) {
        super(s);
    }

    public CityServiceException(String s, Throwable throwable) {
        super(s, throwable);
    }

    public CityServiceException(Throwable throwable) {
        super(throwable);
    }
}
